let context = oEvent.oSource.getBindingContext();
let data = context.getObject();

sap.m.MessageBox.show('Do you want to delete this entry ? ', {
    title: 'Delete',
    icon: sap.m.MessageBox.Icon.ERROR,
    actions: [sap.m.MessageBox.Action.YES, sap.m.MessageBox.Action.CANCEL],
    onClose: function (oAction) {
        if (oAction === 'YES') {            
            report.variantDelete(data.id);
        }
    }
});